# 1. 사이트 기본 정보 (따옴표를 꼭 쓰세요)
title: "Welcome to My Profile!"
description: "Elevating Galaxy User Experience through Camera Solutions"
url: "https://jk-the-ko.github.io" # 본인의 GitHub 주소로 변경

# 2. 테마 설정
remote_theme: "pages-themes/minimal"
google_analytics: ""

# 3. 필수 플러그인 (image_24a2e6 에러 해결 핵심)
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-gist
  - jekyll-feed

# 4. 사용자 정보
avatar: "/assets/profile.jpg"

# 소셜 링크 및 계정 정보
github_username: "JK-the-Ko"
linkedin_username: "jaekyun-ko"
google_scholar: "NBs5cTMAAAAJ"
