title: "Jaekyun Ko"
description: "AI ISP Researcher @ Samsung Electronics (Mobile eXperience)"
remote_theme: "mmistakes/minimal-mistakes"
google_analytics: ""

# 프로필 이미지 설정 (이미지 파일은 assets/images/ 폴더에 업로드하세요)
avatar: "/assets/images/profile.jpg"

# 소셜 링크 및 계정 정보
github_username: "JK-the-Ko"
linkedin_username: "jaekyun-ko"
google_scholar: "NBs5cTMAAAAJ" # 구글 스칼라 URL의 user= 뒷부분 ID 입력
